title = "Maxime Letemple"

base_url = "https://mletemple.fr"
theme = "duckquill"
compile_sass = true
generate_feeds = true
build_search_index = true
minify_html = true

default_language = "fr"
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true

[search]
index_format = "elasticlunr_json"

[languages.en]
title = "Maxime Letemple"
generate_feeds = true

taxonomies = [{ name = "tags", feed = true }]

[extra]
default_theme = "light"
accent_color = "#26A269"
accent_color_alpha = "rgb(38 162 105 / 0.2)"
katex = true
show_copy_button = true

[extra.nav]
show_feed = true
show_repo = true
links = [
  # {url = "https://codeberg.org/daudix/duckquill", name = "Repo"},
  #  {url = "$BASE_URL/demo", name = "Demo"},
  { url = "@/blog/_index.md", name = "Blog" },
  { name = "Contact", menu = [
    { url = "https://github.com/maxletemple", name = "GitHub" },
    { url = "https://www.linkedin.com/in/maxime-letemple-186006162/", name = "LinkedIn" },
    { url = "CV.pdf", name = "CV" },
    # { url = "mailto:maxime.letemple@bordeaux-inp.fr", name = "Mail" },
  ]},
]
show_theme_switcher = true

[extra.footer]
show_copyright = true
show_powered_by = true
